version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=oadb
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=apppass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d oadb"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build: ./app/api
    env_file:
      - .env
      - .env.local
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./data:/app/data

  worker:
    build: ./app/api
    env_file:
      - .env
      - .env.local
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    command: rq worker -u redis://redis:6379/0 default
    volumes:
      - ./data:/app/data

  frontend:
    build: ./app/frontend
    env_file:
      - .env
      - .env.local
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./app/frontend:/app
      - /app/node_modules

volumes:
  dbdata:
