version: "3.8"

services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=oadb
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=apppass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d oadb"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - dbdata:/var/lib/postgresql/data

  api:
    build: ./app/api
    environment:
      - APP_VERSION=0.1.0
      - PYTHONPATH=/app/src
      - DATABASE_URL=postgresql+psycopg://appuser:apppass@db:5432/oadb
      - DATA_DIR=/app/data/raw            # NEW: your app can read/write here
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./data:/app/data                  # NEW: host ./data ↔ container /app/data

volumes:
  dbdata:
